image: Visual Studio 2019
platform:
  - x86
  - x64
configuration: Release

build_script:
  - cmd: cmake -H. -B_build
  - cmd: cmake --build _build --config Release
  - cmd: cd _build
  - cmd: ls
  - cmd: cpack -G NSIS
  - cmd: cd ..

artifacts:
  - path: ./_build/*.msi
    name: solver
deploy:
  release: 
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: pn88ttofsx9h97p1rwm5
  artifact: print
  on:
    APPVEYOR_REPO_TAG: true
